### PR TITLE
Added showZero option

### PR DESCRIPTION
**Pull request by ChrisKatsaras**
I found that when I was making my pie chart, I didn't like that %0 slices would still have a label. I decided the best fix for this was to implement a showZero option

**showZero** - Boolean that defaults to false.

**showZero : true**
screen shot 2017-06-22 at 10 58 09 am

**showZero: false**

screen shot 2017-06-22 at 10 56 03 am

Love Chart.PieceLabel.js and happy to contribute to it! 😄

### CODE REVIEW

**Comment by emn178** [comment]
what about value is 0? I think it should also apply this feature.

**Comment by ChrisKatsaras** [comment]
Just to clarify? You would like the showZero option to also hide values on zero if  
`mode = value` ? If this is the case, I think this is an excellent idea and I can implement it soon! 😃

**Comment by emn178** [comment]
yes, I think all modes should hide if value is 0. we can simply skip the for loop if the current value is 0.

**Comment by ChrisKatsaras** [comment]
@emn178 showZero option should now work with all 3 modes! 😄

**Pull request merged**
