### PR TITLE
Support for horizontal bar chart 

### PR DESCRIPTION
**Pull request by qubiack**

### CODE REVIEW

**Comment by qubiack** [comment]
If you are interested with this feature - pleas let me know about it. I change some things just for my needs so I can prepare version compatible with your if you want it.

**Comment by dharitdesai** [comment]
can we have this added please ?

**Comment by qubiack** [comment]
I need 2 weeks to prepare version compatible with your plugin, because I prepare a lot of changes only for specific project, not acceptable in public project. I will create new pull request whith this changes, and let you know about it.

**Comment by JeSuisUnCaillou** [comment]
Any news about your horizontalBar support ?

**Comment by baroninn** [comment]
Any news about your horizontalBar support ?

**Pull request closed without merging**
