### PR TITLE
Adding label parameter to value format function

### PR DESCRIPTION
**Pull request by nicole-brooks**
By adding the label parameter to the value format function, a user can display both the correctly-formatted value and the label outside the chart.

### CODE REVIEW

**Comment by emn178** [comment]
I plan to add custom mode like this
```JavaScript
mode: function (args) {
  args // {value: 123, label: 'Something', percentage: 50 }
  return args.label + ': ' + args.value;
}
```
and deprecate `format` options. It should be more flexible.

**Comment by dteske25** [comment]
When would you be able to get around to this?

**Comment by emn178** [comment]
I think It will be done in couple days.

**Comment by emn178** [comment]
you can use render function to do this in v0.7.0.

**Pull request closed without merging**
